// LONG AI v1.5.1: discovery with partial results, controlled concurrency and transparent errors.
const STOCKS=['UBER','GTLB','OXY','SNOW','CRM','ABBV','PEP','CVX','RTX','HAE','NVDA','MU','ANET','COHR','PLTR','FROG','RKLB','APLD','PANW','CRWD','MSFT','GOOGL','AMZN','META','AAPL','AMD','AVGO','TSM','ASML','AMAT','LRCX','KLAC','MRVL','SMCI','ORCL','NET','DDOG','SHOP','NOW','INTU','RBRK','ZS','FTNT','OKTA','PATH','MDB','HUBS','TWLO','HOOD','COIN','MSTR','SQ','PYPL','SOFI','AFRM','IBKR','GS','JPM','BAC','C','XOM','SLB','HAL','KOS','COP','EOG','MPC','VLO','GEV','ETN','PWR','VST','CEG','BE','OKLO','CCJ','NEE','DUK','GE','CAT','DE','URI','BA','LMT','NOC','KTOS','HIMS','TEM','UNH','LLY','MRK','PFE','GILD','REGN','TMO','ISRG','DXCM','ROST','COST','WMT','TGT','HD','LOW','CMG','MCD','SBUX','NFLX','DIS','SPOT','ROKU','TTD','ABNB','BKNG','RCL','CCL','DAL','UAL','TSLA','RIVN','LCID','NIO','F','GM'];
const TIMEOUT=6500;
async function get(url){const c=new AbortController();const timer=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json','User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer)}}
function iso(t){let n=Number(t);if(n>1e12)n/=1000;return Number.isFinite(n)&&n>1e9&&n<5e9?new Date(n*1000).toISOString():null}
async function stock(s){let reason='proveïdor sense dades';for(const host of ['query1','query2']){try{const x=(await get(`https://${host}.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?interval=1d&range=7d`))?.chart?.result?.[0];if(!x){reason='resposta sense dades';continue}const m=x.meta||{},q=x.indicators?.quote?.[0]||{},close=(q.close||[]).filter(v=>Number.isFinite(v)),vol=(q.volume||[]).filter(v=>Number.isFinite(v));const p=Number(m.regularMarketPrice)||close.at(-1),prev=Number(m.chartPreviousClose||m.previousClose)||close.at(-2),volume=vol.at(-1)||0;if(!(p>0&&prev>0)){reason='preu anterior o actual absent';continue}return {symbol:s,type:'acció',price:p,changePct:100*(p/prev-1),dollarVolume:p*volume,quoteTime:iso(m.regularMarketTime)||iso(x.timestamp?.at(-1)),source:'Yahoo Finance',status:'WATCH',verifiedSignal:false}}catch(e){reason=e.message||'error desconegut'}}throw Error(s+': '+reason)}
async function coingecko(){const d=await get('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=volume_desc&per_page=100&page=1&sparkline=false&price_change_percentage=24h');if(!Array.isArray(d))throw Error('resposta invàlida');return d.filter(x=>x.symbol&&x.current_price>0&&x.total_volume>1000000&&x.id!=='bitcoin').map(x=>({symbol:x.symbol.toUpperCase(),type:'cripto',name:x.name,coinId:x.id,price:x.current_price,changePct:x.price_change_percentage_24h,dollarVolume:x.total_volume,quoteTime:x.last_updated,source:'CoinGecko',status:'WATCH',verifiedSignal:false}))}
async function binance(){const raw=await get('https://api.binance.com/api/v3/ticker/24hr');if(!Array.isArray(raw))throw Error('resposta invàlida');const banned=/^(USDC|USDT|FDUSD|TUSD|DAI|EUR|USD|BUSD|WBTC|BTC)$/;return raw.filter(x=>x.symbol?.endsWith('USDT')&& !banned.test(x.symbol.slice(0,-4))).map(x=>({symbol:x.symbol.slice(0,-4),type:'cripto',price:Number(x.lastPrice),changePct:Number(x.priceChangePercent),dollarVolume:Number(x.quoteVolume),quoteTime:iso(x.closeTime),source:'Binance 24h',status:'WATCH',verifiedSignal:false})).filter(x=>x.price>0&&x.dollarVolume>1000000)}
function rank(a){return Math.max(-12,Math.min(12,Number(a.changePct)||0))*1.3+Math.min(13,Math.log10(Math.max(1,a.dollarVolume||1)))*1.5}
async function stockBatch(symbols){const out=[],errors=[];for(let i=0;i<symbols.length;i+=5){const settled=await Promise.allSettled(symbols.slice(i,i+5).map(stock));settled.forEach((r,j)=>r.status==='fulfilled'?out.push(r.value):errors.push(String(r.reason?.message||r.reason)))}return {out,errors}}
export default async function handler(req,res){res.setHeader('Cache-Control','public,s-maxage=60,stale-while-revalidate=120');if(req.method!=='GET')return res.status(405).json({error:'method_not_allowed'});const offset=Math.max(0,parseInt(req.query?.offset||'0',10)||0)%STOCKS.length;const count=Math.min(20,Math.max(5,parseInt(req.query?.count||'15',10)||15));const sample=Array.from({length:count},(_,i)=>STOCKS[(offset+i)%STOCKS.length]);const [equity,coin]=await Promise.allSettled([stockBatch(sample),(async()=>{try{return await coingecko()}catch(e){try{return await binance()}catch(f){throw Error('CoinGecko: '+e.message+'; Binance: '+f.message)}}})()]);const stocks=equity.status==='fulfilled'?equity.value.out:[];const cryptos=coin.status==='fulfilled'?coin.value:[];const errors=[...(equity.status==='fulfilled'?equity.value.errors:[String(equity.reason)])];if(coin.status==='rejected')errors.push(String(coin.reason));const now=Date.now();const fresh=x=>{const t=Date.parse(x.quoteTime||'');return Number.isFinite(t)&&t<=now+600000&&now-t<(x.type==='acció'?5*86400000:2*3600000)};const result={stocks:stocks.filter(fresh).sort((a,b)=>rank(b)-rank(a)).slice(0,10),crypto:cryptos.filter(fresh).sort((a,b)=>rank(b)-rank(a)).slice(0,10),coverage:{stockCandidates:sample.length,stockQuotes:stocks.length,cryptoQuotes:cryptos.length,stockUniverse:STOCKS.length,cryptoUniverse:100,offset},errors:errors.slice(0,12),updatedAt:new Date().toISOString(),rotation:'Rotació de '+count+' accions per consulta',warning:'Descoberta orientativa; WATCH no és senyal de compra.'};if(!result.stocks.length&&!result.crypto.length)return res.status(503).json({...result,error:'No hi ha dades recents disponibles en cap proveïdor.'});return res.status(200).json(result)}
