const STOCKS=['UBER','GTLB','OXY','SNOW','CRM','ABBV','PEP','CVX','RTX','HAE'];
const CRYPTOS={BTC:'bitcoin',ETH:'ethereum',SOL:'solana',AVAX:'avalanche-2',AAVE:'aave',LINK:'chainlink',UNI:'uniswap',DOGE:'dogecoin',LTC:'litecoin',BCH:'bitcoin-cash'};
const allowed=new Set([...STOCKS,...Object.keys(CRYPTOS)]);
const validStock=s=>/^[A-Z][A-Z0-9.\-]{0,9}$/.test(s);
const wait=(p,ms=9500)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),ms))]);
async function json(url){let r=await wait(fetch(url,{headers:{'User-Agent':'LongAIDashboard/1.1','Accept':'application/json'}}));if(!r.ok)throw new Error('provider_http_'+r.status);return r.json()}
async function stock(symbol){let d=await json('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?interval=1d&range=5d');let x=d?.chart?.result?.[0];if(!x)throw Error('missing_stock');let meta=x.meta||{},price=Number(meta.regularMarketPrice),prev=Number(meta.chartPreviousClose||meta.previousClose);if(!(price>0))throw Error('missing_price');return {symbol,type:'acció',price,changePct:prev>0?100*(price/prev-1):null,marketState:meta.marketState||null,quoteTime:meta.regularMarketTime?new Date(meta.regularMarketTime*1000).toISOString():null,source:'Yahoo Finance chart (consulta pública)',status:'WATCH',verifiedSignal:false}}
async function cryptos(){let ids=Object.values(CRYPTOS).join(',');let d=await json('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids='+ids+'&price_change_percentage=24h');return d.map(x=>({symbol:Object.keys(CRYPTOS).find(k=>CRYPTOS[k]===x.id),type:'cripto',price:x.current_price,changePct:x.price_change_percentage_24h,quoteTime:x.last_updated,source:'CoinGecko',status:'WATCH',verifiedSignal:false})).filter(x=>x.symbol&&Number.isFinite(x.price))}
export default async function handler(req,res){res.setHeader('Cache-Control','public, s-maxage=45, stale-while-revalidate=90');if(req.method!=='GET')return res.status(405).json({error:'method_not_allowed'});let selected=String(req.query?.symbols||'').split(',').map(s=>s.trim().toUpperCase()).filter(s=>allowed.has(s)||validStock(s));if(!selected.length)selected=[...STOCKS,...Object.keys(CRYPTOS)];selected=[...new Set(selected)].slice(0,20);const eq=selected.filter(s=>!CRYPTOS[s]),coins=selected.filter(s=>CRYPTOS[s]);const out=await Promise.allSettled([Promise.allSettled(eq.map(stock)),coins.length?cryptos():Promise.resolve([])]);let quotes=[],errors=[];if(out[0].status==='fulfilled')out[0].value.forEach((x,i)=>x.status==='fulfilled'?quotes.push(x.value):errors.push({symbol:eq[i],reason:String(x.reason?.message||x.reason)}));else errors.push({source:'stocks',reason:String(out[0].reason)});if(out[1].status==='fulfilled')quotes.push(...out[1].value.filter(x=>coins.includes(x.symbol)));else errors.push({source:'crypto',reason:String(out[1].reason?.message||out[1].reason)});return res.status(quotes.length?200:503).json({quotes,errors,updatedAt:new Date().toISOString(),mode:'live_quotes_only',disclaimer:'Quotes no equivalen a senyals Pine READY; validar data/marketState abans d’operar.'})}
