// LONG AI 1.2 — Escàner orientatiu, NO replica exacta del Pine v6.4.1.
// Càlculs server-side, sense claus ni ordres. Font Yahoo Finance Chart per accions;
// Binance public klines per cripto quan la regió ho permet.
const STOCKS=new Set(['UBER','GTLB','OXY','SNOW','CRM','ABBV','PEP','CVX','RTX','HAE','NVDA','MU','ANET','COHR','PLTR','FROG','RKLB','APLD','PANW','CRWD']);
const CRYPTOS=new Set(['BTC','ETH','SOL','AVAX','AAVE','LINK','UNI','DOGE','LTC','BCH','SUI','ONDO','RENDER','NEAR','TIA','XRP','ENA','INJ','ARB','JUP']);
const timeout=async(url)=>{const ctl=new AbortController();const id=setTimeout(()=>ctl.abort(),7000);try{const r=await fetch(url,{signal:ctl.signal,headers:{'Accept':'application/json','User-Agent':'Mozilla/5.0 LONG-AI-Radar'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}finally{clearTimeout(id)}};
function clean(bars){return bars.filter(x=>[x.o,x.h,x.l,x.c,x.v].every(Number.isFinite)&&x.c>0&&x.h>=x.l).sort((a,b)=>a.t-b.t)}
async function yahoo(symbol,interval,range){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?interval=${interval}&range=${range}&includePrePost=false`;const j=await timeout(u),x=j?.chart?.result?.[0],q=x?.indicators?.quote?.[0];if(!q)throw Error('no chart');let b=x.timestamp.map((t,i)=>({t:t*1000,o:q.open[i],h:q.high[i],l:q.low[i],c:q.close[i],v:q.volume[i]}));return clean(b)}
async function binance(symbol,interval,limit){const s=symbol+'USDT',u=`https://api.binance.com/api/v3/klines?symbol=${s}&interval=${interval}&limit=${limit}`;const a=await timeout(u);if(!Array.isArray(a))throw Error('no klines');return clean(a.map(x=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]})))}
function aggregate(a,n){let out=[];for(let i=0;i+n<=a.length;i+=n){const x=a.slice(i,i+n);out.push({t:x[0].t,o:x[0].o,h:Math.max(...x.map(y=>y.h)),l:Math.min(...x.map(y=>y.l)),c:x.at(-1).c,v:x.reduce((s,y)=>s+y.v,0)})}return out}
function ema(a,p){if(a.length<p)return null;let v=a.slice(0,p).reduce((s,x)=>s+x,0)/p,k=2/(p+1);for(let i=p;i<a.length;i++)v=a[i]*k+v*(1-k);return v}
function rsi(a,p=14){if(a.length<p+1)return null;let gain=0,loss=0;for(let i=a.length-p;i<a.length;i++){let d=a[i]-a[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}return loss===0?100:100-100/(1+gain/loss)}
function atr(b,p=14){if(b.length<p+1)return null;let sum=0;for(let i=b.length-p;i<b.length;i++){let x=b[i],prev=b[i-1].c;sum+=Math.max(x.h-x.l,Math.abs(x.h-prev),Math.abs(x.l-prev))}return sum/p}
function macd(a){let e12=ema(a,12),e26=ema(a,26);return e12!==null&&e26!==null?e12-e26:null}
function metrics(b){const c=b.map(x=>x.c),z=b.at(-1);return {price:z?.c??null,ema20:ema(c,20),ema50:ema(c,50),ema200:ema(c,200),rsi:rsi(c),atr:atr(b),macd:macd(c),lastTime:z?.t??null,volume:z?.v??null}}
function analyze(symbol,type,d,h,f){if(d.length<55||h.length<65||f.length<30)return {symbol,type,status:'WATCH',verifiedSignal:false,reason:'Històric insuficient per validar la configuració',coverage:{daily:d.length,hour:h.length,thirty:f.length}};
  const D=metrics(d),H=metrics(h),F=metrics(f),C=f.at(-1),prior=f.slice(-13,-1),high=Math.max(...prior.map(x=>x.h)),low=Math.min(...prior.map(x=>x.l));const vols=f.slice(-21,-1).map(x=>x.v),avgVol=vols.reduce((a,b)=>a+b,0)/(vols.length||1),rvol=avgVol>0?C.v/avgVol:null;
  const higher=D.price>D.ema20&&D.ema20>D.ema50&&H.price>H.ema20&&H.ema20>H.ema50;
  const momentum=F.rsi!==null&&F.rsi>=48&&F.rsi<=72;const breakout=C.c>high&&C.c>C.o;const nearRetest=F.ema20!==null&&C.l<=F.ema20*1.008&&C.c>F.ema20&&C.c>C.o;
  const pattern=breakout?'RUPTURA':nearRetest?'RETEST EMA20':'SENSE PATRÓ';const volOk=rvol!==null&&rvol>=1.35;
  // El nivell d'entrada és una condició indicativa; TP1 només des de resistència històrica verificable.
  let trigger=breakout?C.c:nearRetest?C.h:high,stop=Math.min(low,C.l)-0.18*(F.atr??0),risk=trigger-stop;
  const priorHighs=h.slice(-80,-1).filter(x=>x.h>trigger).map(x=>x.h).sort((a,b)=>a-b);let tp1=priorHighs.length?priorHighs[0]:null;
  // Un TP teòric de 2R no és una resistència real. Si no hi ha TP1 estructural, RR queda desconegut.
  let rr=tp1&&risk>0?(tp1-trigger)/risk:null,tp2=risk>0?trigger+2.5*risk:null;
  let state='WATCH',reason='Tendència o setup insuficient';
  if(higher&&(breakout||nearRetest)){state='PRE-SETUP';reason='Setup identificat; manca confirmació completa de volum, estructura i objectiu';if(volOk&&momentum&&rr!==null&&rr>=2){state='PRE-READY';reason='Múltiples filtres favorables; confirmar amb Pine/TradingView i vela tancada'}}
  // Deliberadament mai marca READY formal sense comprovació completa de les dades del Pine.
  return {symbol,type,status:state,verifiedSignal:false,pattern,reason,price:F.price,trigger:risk>0?trigger:null,stop:risk>0?stop:null,tp1,tp2:tp1?tp2:null,rr,volumeRatio:rvol,trendD:D.price>D.ema20&&D.ema20>D.ema50,trend4H:higher,rsi:F.rsi,ema20:F.ema20,ema50:F.ema50,macd:F.macd,atr:F.atr,quoteTime:new Date(C.t).toISOString(),coverage:{daily:d.length,hour:h.length,thirty:f.length},filters:{higher,momentum,breakout,retest:nearRetest,volume:volOk,rr:rr!==null&&rr>=2},source:type==='acció'?'Yahoo Finance Chart':'Binance public klines',warning:'Anàlisi orientativa, NO senyal oficial Pine. Sense garantia de bid/ask, extensió ni execució.'}}
async function one(symbol){const isStock=STOCKS.has(symbol),isCrypto=CRYPTOS.has(symbol);if(!isStock&&!isCrypto)throw Error('symbol_not_supported');let d,h,f;if(isStock){const x=await Promise.all([yahoo(symbol,'1d','1y'),yahoo(symbol,'60m','3mo'),yahoo(symbol,'30m','1mo')]);d=x[0];h=x[1];f=x[2];const four=aggregate(h,4);return analyze(symbol,'acció',d,four,f)}else{[d,h,f]=await Promise.all([binance(symbol,'1d',260),binance(symbol,'4h',300),binance(symbol,'30m',240)]);return analyze(symbol,'cripto',d,h,f)}}
export default async function handler(req,res){res.setHeader('Cache-Control','public,s-maxage=120,stale-while-revalidate=240');if(req.method!=='GET')return res.status(405).json({error:'method_not_allowed'});const requested=String(req.query?.symbols||'UBER,GTLB,OXY,SNOW,AVAX').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);const names=[...new Set(requested)].slice(0,5);let results=await Promise.allSettled(names.map(one));const analyses=[],errors=[];results.forEach((r,i)=>r.status==='fulfilled'?analyses.push(r.value):errors.push({symbol:names[i],message:String(r.reason?.message||r.reason)}));return res.status(200).json({analyses,errors,updatedAt:new Date().toISOString(),version:'1.2.0',mode:'indicative_technical_screen',important:'Els estats són estimacions del motor web; no són la sortida directa del Pine LONG AI v6.4.1. READY desactivat sense validació completa.'})}
